version: '3.4'

services:
  arcus.apis.bacon:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationInsights_InstrumentationKey=<key>
      - ARCUS_HTTP_PORT=999
    ports:
      - "789:999"
  arcus.ap.gateway:
    environment:
      - config.service.endpoint=<endpoint>
      - config.service.auth=<key>
    ports:
      - "700:8080"